local username = os.getenv("USER") or os.getenv("USERNAME")
require(string.format("%s.plugins-setup", username))
require(string.format("%s.core.colorscheme", username))
require(string.format("%s.core.keymaps", username))
require(string.format("%s.core.options", username))
require(string.format("%s.plugins.comment", username))
require(string.format("%s.plugins.lualine", username))
require(string.format("%s.plugins.nvim-tree", username))
require(string.format("%s.plugins.nvm-dap", username))
require(string.format("%s.plugins.telescope", username))
require(string.format("%s.plugins.nvim-cmp", username))
-- require(string.format("%s.plugins.lsp.java", username))
-- local config = require("plugins.lsp.java").make_jdtls_config()
-- require("jdtls").start_or_attach(config)
-- local config = require(string.format("%s.plugins.lsp.java", username)).make_jdtls_config()
-- require("jdtls").start_or_attach(config)
require(string.format("%s.plugins.lsp.mason", username))
require(string.format("%s.plugins.lsp.lspsaga", username))
require(string.format("%s.plugins.lsp.lspconfig", username))
require(string.format("%s.plugins.lsp.null-ls", username))
require(string.format("%s.plugins.autopairs", username))
require(string.format("%s.plugins.treesitter", username))
require(string.format("%s.plugins.gitsigns", username))
require(string.format("%s.plugins.vim-visual-multi", username))
